[bill]
command=$SCRIPT_DIR/bill
interval=persist

# currency symbol
lead_symbol=$

# either put an annual salary in yearly_amount
# or hourly rate in hourly_amount.
# if both are defined, hourly will be used.
yearly_amount=50000.00
hourly_amount=24.03

# if using yearly_amount, specify the numbers
# of hours worked in a year.
# default is 2080 (aka 40 hour work weeks)
hours_per_year=2080

# maximum number of digits displayed on right
# side of decimal point
decimal_length=2

# how often the display will update (in milliseconds)
# if not defined, defaults to 50
update_rate=50